# Generated by Django 6.0.2 on 2026-07-03 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("computing_core", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="file",
            table="computing_core__file",
        ),
        migrations.AlterModelTable(
            name="ipaddress",
            table="computing_core__ip_address",
        ),
        migrations.AlterModelTable(
            name="networkinterface",
            table="computing_core__network_interface",
        ),
        migrations.AlterModelTable(
            name="port",
            table="computing_core__port",
        ),
        migrations.AlterModelTable(
            name="privatekey",
            table="computing_core__private_key",
        ),
        migrations.AlterModelTable(
            name="program",
            table="computing_core__program",
        ),
        migrations.AlterModelTable(
            name="publickey",
            table="computing_core__public_key",
        ),
        migrations.AlterModelTable(
            name="tcpconnection",
            table="computing_core__tcp_connection",
        ),
        migrations.AlterModelTable(
            name="user",
            table="computing_core__user",
        ),
        migrations.AlterModelTable(
            name="webdocument",
            table="computing_core__web_document",
        ),
        migrations.AlterModelTable(
            name="webhost",
            table="computing_core__web_host",
        ),
    ]
