# Generated by Django 6.0.8 on 2026-09-23 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("computing_core", "0003_retire_renamed_edge_types"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="configuration",
        ),
        migrations.RemoveField(
            model_name="historicalfile",
            name="configuration",
        ),
        migrations.RemoveField(
            model_name="historicalipaddress",
            name="configuration",
        ),
        migrations.RemoveField(
            model_name="historicalnetworkinterface",
            name="configuration",
        ),
        migrations.RemoveField(
            model_name="historicalport",
            name="configuration",
        ),
        migrations.RemoveField(
            model_name="historicalprivatekey",
            name="configuration",
        ),
        migrations.RemoveField(
            model_name="historicalprogram",
            name="configuration",
        ),
        migrations.RemoveField(
            model_name="historicalpublickey",
            name="configuration",
        ),
        migrations.RemoveField(
            model_name="historicaltcpconnection",
            name="configuration",
        ),
        migrations.RemoveField(
            model_name="ipaddress",
            name="configuration",
        ),
        migrations.RemoveField(
            model_name="networkinterface",
            name="configuration",
        ),
        migrations.RemoveField(
            model_name="port",
            name="configuration",
        ),
        migrations.RemoveField(
            model_name="privatekey",
            name="configuration",
        ),
        migrations.RemoveField(
            model_name="program",
            name="configuration",
        ),
        migrations.RemoveField(
            model_name="publickey",
            name="configuration",
        ),
        migrations.RemoveField(
            model_name="tcpconnection",
            name="configuration",
        ),
    ]
